import Foundation

@MainActor
let packetGroups = [
    PacketGroup(handlePath: "/usr/lib/system/libsystem_eligibility.dylib", [
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_GREYMATTER"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_IRON"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "INVALID"),
    ]),
    
    PacketGroup(handlePath: "/System/Library/PrivateFrameworks/AssistantServices.framework/AssistantServices", [
        PacketDefinition("AFDeviceSupportsSystemAssistantExperience"),
        PacketDefinition("AFDeviceSupportsSAEByDeviceCapabilityAndFeatureFlags"),
        PacketDefinition("AFLocaleSupportsSAE"),
        PacketDefinition("AFDeviceSupportsSAE"),
        
        PacketDefinition(packetType: PacketType.PACKET_OBJC, "+[AFFeatureFlags isSystemAssistantExperienceEnabled]"),
        PacketDefinition(packetType: PacketType.PACKET_OBJC, "+[AFFeatureFlags isSAEOverrideEnabled]"),
        PacketDefinition(packetType: PacketType.PACKET_OBJC, "+[CSFAvailability currentAvailability]"),
    ]),
      
    PacketGroup(handlePath: "/usr/lib/system/libsystem_eligibility.dylib", [
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_INVALID"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_TEST"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_LOTX"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_PODCASTS_TRANSCRIPTS"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_GREYMATTER"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_XCODE_LLM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_SEARCH_MARKETPLACES"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_HYDROGEN"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_HELIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_LITHIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_BERYLLIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_BORON"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_CARBON"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_NITROGEN"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_OXYGEN"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_FLUORINE"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_NEON"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_SODIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_MAGNESIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_ALUMINUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_SILICON"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_PHOSPHORUS"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_SULFUR"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_CHLORINE"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_ARGON"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_POTASSIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_CALCIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_SCANDIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_TITANIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_VANADIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_CHROMIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_MANGANESE"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_IRON"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_COBALT"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_NICKEL"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_COPPER"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_ZINC"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_GALLIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_GERMANIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_ARSENIC"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_SELENIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_BROMINE"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_KRYPTON"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_RUBIDIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_STRONTIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_YTTRIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_ZIRCONIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_NIOBIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_MOLYBDENUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_TECHNETIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_RUTHENIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_RHODIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_PALLADIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_SILVER"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_CADMIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_INDIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_TIN"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_ANTIMONY"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_TELLURIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_IODINE"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_XENON"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_CESIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_BARIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_LANTHANUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_CERIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_PRASEODYMIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_NEODYMIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_PROMETHIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_SAMARIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_EUROPIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_GADOLINIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_TERBIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_DYSPROSIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_HOLMIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_ERBIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_THULIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_YTTERBIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_LUTETIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_HAFNIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_TANTALUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_TUNGSTEN"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_RHENIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_OSMIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_IRIDIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_PLATINUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_GOLD"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_MERCURY"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_THALLIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_LEAD"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_BISMUTH"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_POLONIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_ASTATINE"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_RADON"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_FRANCIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_RADIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_ACTINIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_THORIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_PROTACTINIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_URANIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_NEPTUNIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_PLUTONIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_AMERICIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_CURIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_BERKELIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_CALIFORNIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_EINSTEINIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_FERMIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_MENDELEVIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_NOBELIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_LAWRENCIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_RUTHERFORDIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_DUBNIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_SEABORGIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_BOHRIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_HASSIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_MEITNERIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_DARMSTADTIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_ROENTGENIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_COPERNICIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_NIHONIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_FLEROVIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_MOSCOVIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_LIVERMORIUM"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_TENNESSINE"),
        PacketDefinition(packetType: .PACKET_ELIGIBILITY, "OS_ELIGIBILITY_DOMAIN_OGANESSON"),
    ]),
    
    PacketGroup(handlePath: "/usr/lib/system/libsystem_featureflags.dylib", [
        PacketDefinition("_os_feature_enabled_impl", "Siri", "sae_override"),
        PacketDefinition("_os_feature_enabled_impl", "Siri", "sae"),
        PacketDefinition("_os_feature_enabled_impl", "Siri", "assistant_engine"),
        PacketDefinition("_os_feature_enabled_impl", "Siri", "patient_siri"),
        PacketDefinition("_os_feature_enabled_impl", "Siri", "bobble"),
        PacketDefinition("_os_feature_enabled_impl", "Siri", "medoc"),
        PacketDefinition("_os_feature_enabled_impl", "Siri", "siri_state_feedback"),
        PacketDefinition("_os_feature_enabled_impl", "Siri", "FileARadar"),
        PacketDefinition("_os_feature_enabled_impl", "Siri", "continuous_conversation"),
        PacketDefinition("_os_feature_enabled_impl", "Siri", "NanoSiriUIRefresh"),
        PacketDefinition("_os_feature_enabled_impl", "Siri", "scda_trial_boosts"),
        PacketDefinition("_os_feature_enabled_impl", "Siri", "scda_proximity"),
        PacketDefinition("_os_feature_enabled_impl", "Siri", "siri_request_dispatcher"),
        PacketDefinition("_os_feature_enabled_impl", "Siri", "lasso"),
        PacketDefinition("_os_feature_enabled_impl", "Siri", "caballero"),
        PacketDefinition("_os_feature_enabled_impl", "Siri", "sirix"),
        
        PacketDefinition("_os_feature_enabled_impl", "SiriUI", "sae"),
        
        PacketDefinition("_os_feature_enabled_impl", "SiriNL", "NLRouter"),
        
        PacketDefinition("_os_feature_enabled_impl", "GenerativeModels", "GenerativeModelsAvailability"),
        
        PacketDefinition("_os_feature_enabled_impl", "Pommes", "Sphinx"),
        
        PacketDefinition("_os_feature_enabled_impl", "parsecd", "ResponseFramework"),
    ]),
    
    /*
    PacketGroup(handlePath: "/usr/lib/system/libsystem_featureflags.dylib", [
        PacketDefinition("_os_feature_enabled_impl", "PepperUICore", "new_system_margins"),
        
        PacketDefinition("_os_feature_enabled_impl", "GenerativePlayground", "App"),
        
        PacketDefinition("_os_feature_enabled_impl", "Oneness", "App"),
        PacketDefinition("_os_feature_enabled_impl", "Oneness", "Shell"),
        PacketDefinition("_os_feature_enabled_impl", "Oneness", "DragAndDrop"),
        PacketDefinition("_os_feature_enabled_impl", "Oneness", "Accessibility"),

        PacketDefinition("_os_feature_enabled_impl", "AppKit", "Glade"),
        PacketDefinition("_os_feature_enabled_impl", "UIKit", "Pegasus"),
        PacketDefinition("_os_feature_enabled_impl", "UIKit", "keyboard_oop"),
        PacketDefinition("_os_feature_enabled_impl", "UIKit", "global_edge_swipe_touches_ios"),
        PacketDefinition("_os_feature_enabled_impl", "UIKit", "swift_c2"),
        
        PacketDefinition("_os_feature_enabled_impl", "SpotlightUI", "UnifiedKeyboardBackground"),
        
        PacketDefinition("_os_feature_enabled_impl", "Mail", "CatchUp"),
        
        PacketDefinition("_os_feature_enabled_impl", "Photos", "PhotoPickerUsageInfo"),
        
        PacketDefinition("_os_feature_enabled_impl", "SettingsApp", "SettingsUndo"),
        
        PacketDefinition("_os_feature_enabled_impl", "PreferencesFramework", "multiline_cells_enabled"),
        PacketDefinition("_os_feature_enabled_impl", "PreferencesFramework", "modern_layout_enabled"),
        PacketDefinition("_os_feature_enabled_impl", "PreferencesFramework", "inset_table_style_enabled"),
        
        PacketDefinition("_os_feature_enabled_impl", "PerfPowerServices", "battery_health_details"),
        PacketDefinition("_os_feature_enabled_impl", "StorageManagement", "StorageUIV2"),
        
        PacketDefinition("_os_feature_enabled_impl", "ControlCenter", "NewControls"),
        
        PacketDefinition("_os_feature_enabled_impl", "Ensemble", "SystemUIScene"),
        
        PacketDefinition("_os_feature_enabled_impl", "DeviceOSExpert", "SemanticSearch"), // 0
        PacketDefinition("_os_feature_enabled_impl", "Siri", "sae_override"), // 0
        PacketDefinition("_os_feature_enabled_impl", "Siri", "force_uod_enabled_for_device"), // 0
        
        PacketDefinition("_os_feature_enabled_impl", "CoreVideo", "UseIOSurfaceAttachmentsDirectly"), // 0
        
        PacketDefinition("_os_feature_enabled_impl", "NotificationsUI", "ReactiveList"), // 0
        PacketDefinition("_os_feature_enabled_impl", "BulletinBoard", "BulletinBoardRefactor"), // 0
        
        PacketDefinition("_os_feature_enabled_impl", "Messages", "steefm"), // 0
        PacketDefinition("_os_feature_enabled_impl", "Messages", "mdv"), // 0

        PacketDefinition("_os_feature_enabled_impl", "SpringBoard", "AutobahnQuickSwitchTransition"),
        PacketDefinition("_os_feature_enabled_impl", "SpringBoard", "SwiftUITimeAnimation"),
        PacketDefinition("_os_feature_enabled_impl", "SpringBoard", "SooP"),
        PacketDefinition("_os_feature_enabled_impl", "SpringBoard", "SlipSwitch"),
        PacketDefinition("_os_feature_enabled_impl", "SpringBoard", "ShellSceneKit"),
        PacketDefinition("_os_feature_enabled_impl", "SpringBoard", "AHP"),
        PacketDefinition("_os_feature_enabled_impl", "SpringBoard", "ExpansionBoard"),
        PacketDefinition("_os_feature_enabled_impl", "SpringBoard", "Oneness"),
        PacketDefinition("_os_feature_enabled_impl", "SpringBoard", "OnenessHomeScreenEditing"),
        PacketDefinition("_os_feature_enabled_impl", "SpringBoard", "OnenessHomeScreenOnEmbedded"), // 0
        PacketDefinition("_os_feature_enabled_impl", "SpringBoard", "AsynchronousIconImageLoading"), // 0
        PacketDefinition("_os_feature_enabled_impl", "SpringBoard", "Twoness"),
        PacketDefinition("_os_feature_enabled_impl", "SpringBoard", "FlyingScotsman"),
        PacketDefinition("_os_feature_enabled_impl", "SpringBoard", "Dewey"),
        PacketDefinition("_os_feature_enabled_impl", "SpringBoard", "Autobahn"),
        PacketDefinition("_os_feature_enabled_impl", "SpringBoard", "Maglev"),
        PacketDefinition("_os_feature_enabled_impl", "SpringBoard", "Monaco"),
        PacketDefinition("_os_feature_enabled_impl", "SpringBoard", "WooP"),
        PacketDefinition("_os_feature_enabled_impl", "SpringBoard", "SystemUIScene"),
        PacketDefinition("_os_feature_enabled_impl", "SpringBoard", "TraitsArbiterWallpaperTokyoDrift"),
        PacketDefinition("_os_feature_enabled_impl", "SpringBoard", "Meatballs"),
        PacketDefinition("_os_feature_enabled_impl", "SpringBoard", "support_scene_reconnect"),
        PacketDefinition("_os_feature_enabled_impl", "SpringBoard", "StatusBarReusePool"),
        PacketDefinition("_os_feature_enabled_impl", "SpringBoard", "Domino"),
        PacketDefinition("_os_feature_enabled_impl", "SpringBoard", "SuperDomino"),
        PacketDefinition("_os_feature_enabled_impl", "SpringBoard", "FlagOnThePlay"),
        PacketDefinition("_os_feature_enabled_impl", "SpringBoard", "FlagMeDown"),
    ]),
     */
    
    PacketGroup(handlePath: "/usr/lib/system/libsystem_darwin.dylib", [
        PacketDefinition("os_variant_has_internal_diagnostics"),
        PacketDefinition("os_variant_has_internal_content"),
        PacketDefinition("os_variant_has_internal_ui"),
        PacketDefinition("os_variant_has_factory_content"),
        PacketDefinition("os_variant_allows_internal_security_policies"),
        PacketDefinition("os_variant_allows_security_research"),
        PacketDefinition("os_variant_is_darwinos"),
        PacketDefinition("os_variant_is_recovery"),
        PacketDefinition("os_variant_uses_ephemeral_storage"),
    ]),
    
    PacketGroup(handlePath: "/usr/lib/libMobileGestalt.dylib", [
        /*
        PacketDefinition("MobileGestalt_get_appleInternalInstallCapability"),
        PacketDefinition("MobileGestalt_get_internalBuild"),
        PacketDefinition("MobileGestalt_get_hasInternalSettingsBundle"),
        PacketDefinition("MobileGestalt_get_isEmulatedDevice"),
        PacketDefinition("MobileGestalt_get_isVirtualDevice"),
        PacketDefinition("MobileGestalt_get_isSimulator"),
        PacketDefinition("MobileGestalt_get_storeDemoMode"),
        PacketDefinition("MGGetBoolAnswer", "apple-internal-install"),
        PacketDefinition("MGGetBoolAnswer", "ulMliLomP737aAOJ/w/evA"),
        PacketDefinition("MGGetBoolAnswer", "HasInternalSettingsBundle"),
        PacketDefinition("MGGetBoolAnswer", "SBCanForceDebuggingInfo"),
        PacketDefinition("MGGetBoolAnswer", "SBAllowSensitiveUI"),
        */
        PacketDefinition("MGGetBoolAnswer", "IsSimulator"),
        
        PacketDefinition("MGGetBoolAnswer", "DeviceSupportsGrey"),
        PacketDefinition("MGGetBoolAnswer", "8Vbp0HyqndjWuIFZibhu7g"),
        
        PacketDefinition("MGGetBoolAnswer", "DeviceSupportsGenerativeModelSystems"),
        PacketDefinition("MGGetBoolAnswer", "A62OafQ85EJAiiqKn4agtg"),
        
        PacketDefinition("MGGetBoolAnswer", "DeviceSupportsANE"),
        PacketDefinition("MGGetBoolAnswer", "+N9mZUAHooNvMiQnjeTJ8g"),
        
        
        PacketDefinition("MGCopyAnswer", "ReleaseType", isStringReturnType: true),
        PacketDefinition("MGCopyAnswer", "ProductType", isStringReturnType: true),
        PacketDefinition("MGCopyAnswer", "RegionCode", isStringReturnType: true),
        PacketDefinition("MGCopyAnswer", "RegionInfo", isStringReturnType: true),
    ]),
    
    PacketGroup(handlePath: "/System/Library/PrivateFrameworks/BaseBoard.framework/BaseBoard", [
        PacketDefinition("_BSIsInternalInstall"),
        PacketDefinition("_BSHasInternalSettings"),
        PacketDefinition(packetType: PacketType.PACKET_OBJC, "-[BSPlatform isInternalInstall]"),
        PacketDefinition(packetType: PacketType.PACKET_OBJC, "-[BSPlatform isInternalBuild]"),
        PacketDefinition(packetType: PacketType.PACKET_OBJC, "-[BSPlatform isCarrierBuild]"),
        PacketDefinition(packetType: PacketType.PACKET_OBJC, "-[BSPlatform isInternalOrCarrierBuild]"),
        PacketDefinition(packetType: PacketType.PACKET_OBJC, "-[BSPlatform test]"),
        
        PacketDefinition("_BSIsInternalInstall"),
        PacketDefinition("_BSHasInternalSettings"),
        PacketDefinition(packetType: PacketType.PACKET_OBJC, "-[BSPlatform isInternalInstall]"),
        PacketDefinition(packetType: PacketType.PACKET_OBJC, "-[BSPlatform isInternalBuild]"),
        PacketDefinition(packetType: PacketType.PACKET_OBJC, "-[BSPlatform isCarrierBuild]"),
        PacketDefinition(packetType: PacketType.PACKET_OBJC, "-[BSPlatform isInternalOrCarrierBuild]"),
        PacketDefinition(packetType: PacketType.PACKET_OBJC, "-[BSPlatform test]"),
        PacketDefinition("_BSIsInternalInstall"),
        PacketDefinition("_BSHasInternalSettings"),
        PacketDefinition(packetType: PacketType.PACKET_OBJC, "-[BSPlatform isInternalInstall]"),
        PacketDefinition(packetType: PacketType.PACKET_OBJC, "-[BSPlatform isInternalBuild]"),
        PacketDefinition(packetType: PacketType.PACKET_OBJC, "-[BSPlatform isCarrierBuild]"),
        PacketDefinition(packetType: PacketType.PACKET_OBJC, "-[BSPlatform isInternalOrCarrierBuild]"),
        PacketDefinition(packetType: PacketType.PACKET_OBJC, "-[BSPlatform test]"),
    ])
    
]
